@startuml
'https://plantuml.com/class-diagram

interface IPayMode {
    +boolean security(String uId);
}

class PayFaceMode implements IPayMode{
    +boolean security(String uId);
}

class PayFingerprintMode implements IPayMode{
    +boolean security(String uId);
}

abstract class Pay{
   -IPayMode payMode;
   +Pay(IPayMode payMode)
   {abstract} String transfer(String uId,  BigDecimal amount);
}


class WxPay extends Pay{

    +WxPay(IPayMode payMode);
    #String transfer(String uId, BigDecimal amount){};
}

class ZfbPay extends Pay{

    +ZfbPay(IPayMode payMode);
    #String transfer(String uId, BigDecimal amount){};
}

Pay -> IPayMode

@enduml